### PR TITLE
Add some text for the optim. part

### PR DESCRIPTION
**Pull request by dirkschumacher**

### CODE REVIEW

**Comment by derhuerst** [comment]
LGTM. @juliuste opinions? your part?

**Comment by dirkschumacher** [comment]
@juliuste can you write a paragraph about your heuristic? But it's not open source, is it? IS IT?

**Comment by derhuerst** [comment]
@juliuste bump.

**Comment by juliuste** [comment]
@derhuerst See the group chat

**Comment by derhuerst** [comment]
I was rather asking for your opinion on this PR. nevermind, i'll merge.

**Pull request merged**
